server:
  port: 8888
spring:
  redis:
    host: localhost
    password:
    port: 6379
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: hystrix_route
        uri: lb://producer
        predicates:
        - Path=/abc
        filters:
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/error


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug